services:
  db:
    image: postgres:15
    container_name: task_db
    environment:
      POSTGRES_DB: task_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d task_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  db-init:
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      - DB_HOST=db
      - POSTGRES_DB=task_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    depends_on:
      db:
        condition: service_healthy

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/task_db
    depends_on:
      db-init:
        condition: service_completed_successfully
    volumes:
      - ./backend:/app/backend
      - ./common:/app/common

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app/frontend
      - ./common:/app/common

  dev-tools:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: dev_tools_container
    volumes:
      - .:/app:cached
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://user:pass@db:5432/task_db
    command: sleep infinity

networks:
  default:
    name: t2t_default
    external: true